# Use a base image with JDK 20
FROM eclipse-temurin:20-jdk-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the built jar file from the target directory to the container
COPY target/springboot-0.0.1-SNAPSHOT.jar app.jar

# Expose the port your Spring Boot application runs on
EXPOSE 8080

# Command to run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
