# Use the official MySQL image from the Docker Hub
FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=sql123!R
ENV MYSQL_DATABASE=eco-mdb
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=sql123!R

# Expose the default MySQL port
EXPOSE 3306